[package]
name = "threadless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
libaes = "0.6.4"
dinvoke = { path = "../DInvoke_rs/dinvoke_rs/dinvoke" }
clap = { version = "4.3.5", features = ["derive"] }

[dependencies.windows]
version = "0.48"
features = [
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Memory",
    "Win32_System_WindowsProgramming",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Kernel",
    "Win32_System_SystemServices",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Time",
    "Win32_System_LibraryLoader"

]